// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'5cb522cf1d1403f6b2dc85cb65affb8a33f6c42b2e0636a1b3f8c0e7932aa699'>;
export type ExecutionHash =
  ExecutionHashBase<'40c6768f340a8988dc9c7ff945077a225259ca4f2d0ec1d3c607d2b80fe577c1'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AlatBahan: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly namaBarang: CodecTypes['pg/text@1']['output'];
      readonly kuantitas: CodecTypes['pg/int4@1']['output'];
      readonly kondisi: 'BAIK' | 'KARATAN' | 'RUSAK';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly idKategori: CodecTypes['pg/int4@1']['output'] | null;
      readonly idLokasi: CodecTypes['pg/int4@1']['output'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly ItemTag: {
      readonly idItem: CodecTypes['pg/text@1']['output'];
      readonly idTag: CodecTypes['pg/int4@1']['output'];
    };
    readonly Kategori: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly namaKategori: CodecTypes['pg/text@1']['output'];
      readonly deskripsi: CodecTypes['pg/text@1']['output'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['output'];
    };
    readonly LogMutasi: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly jumlahPerubahan: CodecTypes['pg/int4@1']['output'];
      readonly tipe: 'IN' | 'OUT' | 'AUDIT';
      readonly keterangan: CodecTypes['pg/text@1']['output'] | null;
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly idItem: CodecTypes['pg/text@1']['output'];
    };
    readonly LokasiPenyimpanan: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly namaLokasi: CodecTypes['pg/text@1']['output'];
      readonly spesifikLetak: CodecTypes['pg/text@1']['output'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['output'];
    };
    readonly Tag: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly namaTag: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AlatBahan: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly namaBarang: CodecTypes['pg/text@1']['input'];
      readonly kuantitas: CodecTypes['pg/int4@1']['input'];
      readonly kondisi: 'BAIK' | 'KARATAN' | 'RUSAK';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly idKategori: CodecTypes['pg/int4@1']['input'] | null;
      readonly idLokasi: CodecTypes['pg/int4@1']['input'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly ItemTag: {
      readonly idItem: CodecTypes['pg/text@1']['input'];
      readonly idTag: CodecTypes['pg/int4@1']['input'];
    };
    readonly Kategori: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly namaKategori: CodecTypes['pg/text@1']['input'];
      readonly deskripsi: CodecTypes['pg/text@1']['input'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['input'];
    };
    readonly LogMutasi: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly jumlahPerubahan: CodecTypes['pg/int4@1']['input'];
      readonly tipe: 'IN' | 'OUT' | 'AUDIT';
      readonly keterangan: CodecTypes['pg/text@1']['input'] | null;
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly idItem: CodecTypes['pg/text@1']['input'];
    };
    readonly LokasiPenyimpanan: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly namaLokasi: CodecTypes['pg/text@1']['input'];
      readonly spesifikLetak: CodecTypes['pg/text@1']['input'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['input'];
    };
    readonly Tag: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly namaTag: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly alat_bahan: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly idKategori: CodecTypes['pg/int4@1']['output'] | null;
      readonly idLokasi: CodecTypes['pg/int4@1']['output'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['output'] | null;
      readonly kondisi: 'BAIK' | 'KARATAN' | 'RUSAK';
      readonly kuantitas: CodecTypes['pg/int4@1']['output'];
      readonly namaBarang: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly item_tags: {
      readonly idItem: CodecTypes['pg/text@1']['output'];
      readonly idTag: CodecTypes['pg/int4@1']['output'];
    };
    readonly kategori: {
      readonly deskripsi: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idUser: CodecTypes['pg/int4@1']['output'];
      readonly namaKategori: CodecTypes['pg/text@1']['output'];
    };
    readonly log_mutasi: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly idItem: CodecTypes['pg/text@1']['output'];
      readonly jumlahPerubahan: CodecTypes['pg/int4@1']['output'];
      readonly keterangan: CodecTypes['pg/text@1']['output'] | null;
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly tipe: 'IN' | 'OUT' | 'AUDIT';
    };
    readonly lokasiPenyimpanan: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idUser: CodecTypes['pg/int4@1']['output'];
      readonly namaLokasi: CodecTypes['pg/text@1']['output'];
      readonly spesifikLetak: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly tag: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly namaTag: CodecTypes['pg/text@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly alat_bahan: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly idKategori: CodecTypes['pg/int4@1']['input'] | null;
      readonly idLokasi: CodecTypes['pg/int4@1']['input'] | null;
      readonly idUser: CodecTypes['pg/int4@1']['input'] | null;
      readonly kondisi: 'BAIK' | 'KARATAN' | 'RUSAK';
      readonly kuantitas: CodecTypes['pg/int4@1']['input'];
      readonly namaBarang: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly item_tags: {
      readonly idItem: CodecTypes['pg/text@1']['input'];
      readonly idTag: CodecTypes['pg/int4@1']['input'];
    };
    readonly kategori: {
      readonly deskripsi: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idUser: CodecTypes['pg/int4@1']['input'];
      readonly namaKategori: CodecTypes['pg/text@1']['input'];
    };
    readonly log_mutasi: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly idItem: CodecTypes['pg/text@1']['input'];
      readonly jumlahPerubahan: CodecTypes['pg/int4@1']['input'];
      readonly keterangan: CodecTypes['pg/text@1']['input'] | null;
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly tipe: 'IN' | 'OUT' | 'AUDIT';
    };
    readonly lokasiPenyimpanan: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idUser: CodecTypes['pg/int4@1']['input'];
      readonly namaLokasi: CodecTypes['pg/text@1']['input'];
      readonly spesifikLetak: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly tag: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly namaTag: CodecTypes['pg/text@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly alat_bahan: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly namaBarang: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly kuantitas: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly kondisi: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'BAIK'>;
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly idKategori: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly idLokasi: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly idUser: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'alat_bahan_idKategori_idx_f73ca8ee';
                  readonly prefix: 'alat_bahan_idKategori_idx';
                  readonly columns: readonly ['idKategori'];
                  readonly unique: false;
                },
                {
                  readonly name: 'alat_bahan_idLokasi_idx_1d609b10';
                  readonly prefix: 'alat_bahan_idLokasi_idx';
                  readonly columns: readonly ['idLokasi'];
                  readonly unique: false;
                },
                {
                  readonly name: 'alat_bahan_idUser_idx_6acaa521';
                  readonly prefix: 'alat_bahan_idUser_idx';
                  readonly columns: readonly ['idUser'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'alat_bahan';
                    readonly columns: readonly ['idKategori'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'kategori';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'alat_bahan';
                    readonly columns: readonly ['idLokasi'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'lokasiPenyimpanan';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'alat_bahan';
                    readonly columns: readonly ['idUser'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly item_tags: {
              columns: {
                readonly idItem: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly idTag: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['idItem', 'idTag'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'item_tags_idItem_idx_6ba85971';
                  readonly prefix: 'item_tags_idItem_idx';
                  readonly columns: readonly ['idItem'];
                  readonly unique: false;
                },
                {
                  readonly name: 'item_tags_idTag_idx_8040406a';
                  readonly prefix: 'item_tags_idTag_idx';
                  readonly columns: readonly ['idTag'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'item_tags';
                    readonly columns: readonly ['idItem'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'alat_bahan';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'item_tags';
                    readonly columns: readonly ['idTag'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tag';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly kategori: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly namaKategori: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly deskripsi: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly idUser: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'kategori_idUser_idx_6acaa521';
                  readonly prefix: 'kategori_idUser_idx';
                  readonly columns: readonly ['idUser'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'kategori';
                    readonly columns: readonly ['idUser'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly log_mutasi: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly jumlahPerubahan: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tipe: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly keterangan: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tanggal: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly idItem: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'log_mutasi_idItem_idx_6ba85971';
                  readonly prefix: 'log_mutasi_idItem_idx';
                  readonly columns: readonly ['idItem'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'log_mutasi';
                    readonly columns: readonly ['idItem'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'alat_bahan';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly lokasiPenyimpanan: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly namaLokasi: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly spesifikLetak: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly idUser: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'lokasiPenyimpanan_idUser_idx_6acaa521';
                  readonly prefix: 'lokasiPenyimpanan_idUser_idx';
                  readonly columns: readonly ['idUser'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'lokasiPenyimpanan';
                    readonly columns: readonly ['idUser'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly tag: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly namaTag: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['namaTag'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly KondisiBarang: {
              readonly kind: 'valueSet';
              readonly values: readonly ['BAIK', 'KARATAN', 'RUSAK'];
            };
            readonly TipeMutasi: {
              readonly kind: 'valueSet';
              readonly values: readonly ['IN', 'OUT', 'AUDIT'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly kategori: { readonly namespace: 'public' & NamespaceId; readonly model: 'Kategori' };
    readonly lokasiPenyimpanan: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'LokasiPenyimpanan';
    };
    readonly alat_bahan: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AlatBahan';
    };
    readonly log_mutasi: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'LogMutasi';
    };
    readonly tag: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tag' };
    readonly item_tags: { readonly namespace: 'public' & NamespaceId; readonly model: 'ItemTag' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AlatBahan: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly namaBarang: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly kuantitas: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly kondisi: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly idKategori: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idLokasi: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idUser: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly itemTags: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemTag';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idItem'];
                };
              };
              readonly kategori: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Kategori';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idKategori'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly logMutasi: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LogMutasi';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idItem'];
                };
              };
              readonly lokasi: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LokasiPenyimpanan';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idLokasi'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idUser'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'alat_bahan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly namaBarang: { readonly column: 'namaBarang' };
                readonly kuantitas: { readonly column: 'kuantitas' };
                readonly kondisi: { readonly column: 'kondisi' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly idKategori: { readonly column: 'idKategori' };
                readonly idLokasi: { readonly column: 'idLokasi' };
                readonly idUser: { readonly column: 'idUser' };
              };
            };
          };
          readonly ItemTag: {
            readonly fields: {
              readonly idItem: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idTag: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly alatBahan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AlatBahan';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idItem'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly tag: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tag' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idTag'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'item_tags';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idItem: { readonly column: 'idItem' };
                readonly idTag: { readonly column: 'idTag' };
              };
            };
          };
          readonly Kategori: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly namaKategori: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly deskripsi: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idUser: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly alatBahan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AlatBahan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idKategori'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idUser'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'kategori';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly namaKategori: { readonly column: 'namaKategori' };
                readonly deskripsi: { readonly column: 'deskripsi' };
                readonly idUser: { readonly column: 'idUser' };
              };
            };
          };
          readonly LogMutasi: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly jumlahPerubahan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tipe: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly keterangan: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tanggal: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly idItem: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly alatBahan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AlatBahan';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idItem'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'log_mutasi';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly jumlahPerubahan: { readonly column: 'jumlahPerubahan' };
                readonly tipe: { readonly column: 'tipe' };
                readonly keterangan: { readonly column: 'keterangan' };
                readonly tanggal: { readonly column: 'tanggal' };
                readonly idItem: { readonly column: 'idItem' };
              };
            };
          };
          readonly LokasiPenyimpanan: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly namaLokasi: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly spesifikLetak: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idUser: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly alatBahan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AlatBahan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idLokasi'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idUser'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'lokasiPenyimpanan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly namaLokasi: { readonly column: 'namaLokasi' };
                readonly spesifikLetak: { readonly column: 'spesifikLetak' };
                readonly idUser: { readonly column: 'idUser' };
              };
            };
          };
          readonly Tag: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly namaTag: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly itemTags: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemTag';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idTag'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tag';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly namaTag: { readonly column: 'namaTag' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly alatBahan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AlatBahan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idUser'];
                };
              };
              readonly kategori: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Kategori';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idUser'];
                };
              };
              readonly lokasiPenyimpanan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LokasiPenyimpanan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idUser'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly username: { readonly column: 'username' };
                readonly password: { readonly column: 'password' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly KondisiBarang: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'BAIK'; readonly value: 'BAIK' },
              { readonly name: 'KARATAN'; readonly value: 'KARATAN' },
              { readonly name: 'RUSAK'; readonly value: 'RUSAK' },
            ];
          };
          readonly TipeMutasi: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'IN'; readonly value: 'IN' },
              { readonly name: 'OUT'; readonly value: 'OUT' },
              { readonly name: 'AUDIT'; readonly value: 'AUDIT' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'alat_bahan';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'alat_bahan';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'log_mutasi';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
